# TrackLab SoccerNet config
# exp008は　reidはオフ sn_gamestate.team.TeamSiglipUmapKmeans を使うだけ
defaults:
  - dataset: soccernet_gs
  - eval: trackeval
  - engine: offline
  - state: save
  - visualization: gamestate
  - modules/bbox_detector: yolov8
  - modules/reid: prtreid
  - modules/track: bpbreid_strong_sort
  - modules/jersey_number_detect: mmocr
  - modules/team: kmeans_embeddings
  - modules/team_side: mean_position
  - modules/tracklet_agg: voting_role_jn
  - modules/pitch : tvcalib
  - modules/calibration: tvcalib
  - _self_

pipeline: []
  # - bbox_detector
  # - reid
  # - track
  # - pitch
  # - calibration
  # - jersey_number_detect
  # - tracklet_agg
  # - team
  # - team_side

# Experiment name
experiment_name: "sn-gamestate-gsr"

# Path definitions
home_dir: "${oc.env:HOME}"
data_dir: "/local/moriy/SoccerNetGS"
model_dir: "/raid/moriy/model/soccernet/sn-gamestate"

# Machine configuration
num_cores: 4
use_wandb: True
use_rich: True

# wandb kwargs
wandb:
  name: exp008

modules: # Allows module-specific batch_size and other configuration
  bbox_detector: {batch_size: 64}
  pose_bottomup: {batch_size: 64}
  reid: {
    batch_size: 256,
  }
  track: {batch_size: 256}
  pitch: {batch_size: 4}
  calibration: {batch_size: 256, optim_steps: 100}
  jersey_number_detect: {batch_size: 16}
  team: {_target_: sn_gamestate.team.TeamSiglipUmapKmeans}

# Flags
test_tracking: True # If True, pipeline  が実行される
eval_tracking: True #test_tracking と  eval_tracking がどちらもTrueの場合、評価が実行される
print_config: False

# Dataset
dataset:
  nvid: -1  #
  eval_set: "test"
  dataset_path: ${data_dir}/gamestate-2024
  vids_dict:
    valid: []
  track_eval:
    EVAL_SPACE: 'image'

state:
  save_file: null
  load_file: "states/${experiment_name}.pklz"

# Visualization
visualization:
  cfg:
    save_videos: False


project_dir: "${hydra:runtime.cwd}"
hydra:
  output_subdir: "configs"
  job:
    chdir: True
  run:
    dir: "outputs/${experiment_name}/2024-11-19/15-36-49"
  sweep:
    dir: "multirun_outputs/${experiment_name}/2024-11-19/15-36-49"
